### PR TITLE
fix(Elasticsearch): Use HTTP wait strategy

### LINKED ISSUE #1592: [Bug]: Elastic container tests fail randomly
### Testcontainers version

latest (develop branch)

### Using the latest Testcontainers version?

Yes

### Host OS

Windows

### Host arch

x86

### .NET version

10.0.100

### Docker version

```shell
Client:
 Version:           28.4.0
 API version:       1.51
 Go version:        go1.24.7
 Git commit:        d8eb465
 Built:             Wed Sep  3 20:59:40 2025
 OS/Arch:           windows/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.46.0 (204649)
 Engine:
  Version:          28.4.0
  API version:      1.51 (minimum version 1.24)
  Go version:       go1.24.7
  Git commit:       249d679
  Built:            Wed Sep  3 20:57:37 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.27
  GitCommit:        05044ec0a9a75232cad458027ca83437aae3f4da
 runc:
  Version:          1.2.5
  GitCommit:        v1.2.5-0-g59923ef
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client:
 Version:    28.4.0
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  ai: Docker AI Agent - Ask Gordon (Docker Inc.)
    Version:  v1.9.11
    Path:     C:\Program Files\Docker\cli-plugins\docker-ai.exe
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.28.0-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  cloud: Docker Cloud (Docker Inc.)
    Version:  v0.4.27
    Path:     C:\Program Files\Docker\cli-plugins\docker-cloud.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.39.4-desktop.1
    Path:     C:\Users\digital\.docker\cli-plugins\docker-compose.exe
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.42
    Path:     C:\Program Files\Docker\cli-plugins\docker-debug.exe
  desktop: Docker Desktop commands (Docker Inc.)
    Version:  v0.2.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-desktop.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.31
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.4.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  mcp: Docker MCP Plugin (Docker Inc.)
    Version:  v0.20.0
    Path:     C:\Users\digital\.docker\cli-plugins\docker-mcp.exe
  model: Docker Model Runner (Docker Inc.)
    Version:  v0.1.40
    Path:     C:\Program Files\Docker\cli-plugins\docker-model.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.18.3
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 29
 Server Version: 28.4.0
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 CDI spec directories:
  /etc/cdi
  /var/run/cdi
 Discovered Devices:
  cdi: docker.com/gpu=webgpu
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 nvidia
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.6.87.2-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 7.645GiB
 Name: docker-desktop
 ID: b5eca50b-3056-479e-ae12-20c6635810b6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=npipe://\\.\pipe\docker_cli
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```

### What happened?

I noticed that latest [ci run](https://github.com/testcontainers/testcontainers-dotnet/pull/1584/commits/d8103f9a5d9332e8621cdba7fa1ef7bdfa75a5ad) in my draft PR branch had failed Elastic test. The run [before](https://github.com/testcontainers/testcontainers-dotnet/actions/runs/19681176462/job/56375344739?pr=1584) finished without error. Looks like flaky ready check?

I think we need a new wait strategy for Elastic, I'm going to make a separate PR soon.

### Relevant log output

```shell

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by digital88**
## What does this PR do?

Introduces new wait strategy for Elastic container. Fixes #1592

The new wait strategy queries the `/_cluster/health` endpoint and checks that response contains either `yellow` or `green` status. Elastic documentation about `/_cluster/health` endpoint: https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-cluster-health

## Why is it important?

Stops Elastic tests failing randomly in CI.

## How to test this PR?

Run command `dotnet test tests/Testcontainers.Elasticsearch.Tests` from the root of the repo.

### CODE REVIEW

**Review by HofmeisterAn — APPROVED** [review]
Thanks!

File: src/Testcontainers.Elasticsearch/ElasticsearchConfiguration.cs [hunk 1]
```diff
@@ -68,4 +68,27 @@ public ElasticsearchConfiguration(ElasticsearchConfiguration oldValue, Elasticse
...
+    /// </summary>
+    public bool TlsEnabled
+    {
+        get
+        {
+            var hasSecurityEnabled = Environments
+                .TryGetValue("xpack.security.enabled", out var securityEnabled);
+
+            var hasHttpSslEnabled = Environments
+                .TryGetValue("xpack.security.http.ssl.enabled", out var httpSslEnabled);
```
Comment (uladz-zubrycki) [inline src/Testcontainers.Elasticsearch/ElasticsearchConfiguration.cs:83]: This seems to not work for 7.x.x images, which don't have security enabled by default. So even though neither of the `"xpack.security.enabled"` or `"xpack.security.http.ssl.enabled"`environment variables are provided, Elasticsearch still expects HTTP, but `ElasticsearchConfiguration` assumes HTTPS. 

`HttpWaitStrategy` then gets stuck in a loop, as it catches the following exception and returns `false`.
```
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Cannot determine the frame size or a corrupted frame was received.
   at System.Net.Security.SslStream.GetFrameSize(ReadOnlySpan`1 buffer)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.InjectNewHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at HttpWaitStrategy.UntilAsync(IContainer container)
```

Comment (HofmeisterAn) [reply src/Testcontainers.Elasticsearch/ElasticsearchConfiguration.cs:83]: Can you please test and set the environment variables explicitly to `false`?

```csharp
_ = new ElasticsearchBuilder()
    .WithEnvironment("xpack.security.enabled", "false")
    .WithEnvironment("xpack.security.http.ssl.enabled", "false")
    .Build();
```

I believe the expression is incorrect when SSL is not enabled by default. For version 8, you need to disable it explicitly. The `has...` variables will be `false` for images that don't have SSL enabled by default (like version 7).

Comment (uladz-zubrycki) [reply src/Testcontainers.Elasticsearch/ElasticsearchConfiguration.cs:83]: Yes, that's a workaround I ended up with. If variables are there and are set to `false`, then `TlsEnabled` is evaluated to `false` and HTTP is used, just as expected.

Perhaps you need to also check the tag and apply different logic for versions less than 8, where HTTPS is not enabled by default. Or maybe there is some better option.

And possibly handle that specific exception and rethrow it with a clear message indicating protocol mismatch instead of swallowing it.
