### PR TITLE
fix: Prevent a `NullReferenceException` when pulling uncached base images to build an image

### LINKED ISSUE #1125: [Bug]: IFutureDockerImage crashes with NullReferenceException
### Testcontainers version

3.7.0

### Using the latest Testcontainers version?

Yes

### Host OS

Windows

### Host arch

x64

### .NET version

8.0.200

### Docker version

```shell
Client:       Podman Engine
Version:      4.9.2
API Version:  4.9.2
Go Version:   go1.21.6
Git Commit:   f9a48ebcfa9a39144be0f86f4ba842752835f945
Built:        Sat Feb  3 00:29:04 2024
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.7.2
API Version:  4.7.2
Go Version:   go1.20.10
Built:        Tue Oct 31 15:30:11 2023
OS/Arch:      linux/amd64
```

### Docker info

```shell
host:
  arch: amd64
  buildahVersion: 1.32.0
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.7-2.fc38.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 99.9
    systemPercent: 0.05
    userPercent: 0.05
  cpus: 20
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: container
    version: "38"
  eventLogger: journald
  freeLocks: 2046
  hostname: DEGAEWN110264
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.133.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 32038371328
  memTotal: 33493987328
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.8.0-1.fc38.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.8.0
    package: netavark-1.8.0-2.fc38.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.8.0
  ociRuntime:
    name: crun
    package: crun-1.11.2-1.fc38.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.11.2
      commit: ab0edeef1c331840b025e8f1d38090cfb8a0509d
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20231107.g56d9f6d-1.fc38.x86_64
    version: |
      pasta 0^20231107.g56d9f6d-1.fc38.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.2-1.fc38.x86_64
    version: |-
      slirp4netns version 1.2.2
      commit: 0ee2d87523e906518d34a6b423271e4826f71faf
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 8589934592
  swapTotal: 8589934592
  uptime: 1h 59m 27.00s (Approximately 0.04 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 1081101176832
  graphRootUsed: 2069975040
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 18
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.7.2
  Built: 1698762611
  BuiltTime: Tue Oct 31 15:30:11 2023
  GitCommit: ""
  GoVersion: go1.20.10
  Os: linux
  OsArch: linux/amd64
  Version: 4.7.2
```

### What happened?

Image creation fails with NullRefrenceException

### Relevant log output

_No response_

### Additional information

Could locate issue in source, will provide a PR

### PR DESCRIPTION
**Pull request by tom-englert**
## What does this PR do?

Fix a possible null reference exception when the `RepoTags` property of the `ImagesListResponse` is null.

## Why is it important?

Repeated crashes in tests when the docker instance in not empty makes it unusable 

## Related issues
- Closes #1125

## How to test this PR

Unfortunately I could not find a public reproducible way, only with some company internal images. 
However the fix is minimal and self explaining, just adding a null check.

### CODE REVIEW

File: src/Testcontainers/Clients/TestcontainersClient.cs [hunk 1]
```diff
@@ -339,7 +339,7 @@ public async Task<string> BuildAsync(IImageFromDockerfileConfiguration configura
         var cachedImages = await Image.GetAllAsync(filters, ct)
           .ConfigureAwait(false);
 
-        var repositoryTags = new HashSet<string>(cachedImages.SelectMany(image => image.RepoTags));
+        var repositoryTags = new HashSet<string>(cachedImages.SelectMany(image => image.RepoTags ?? Array.Empty<string>()));
```
Comment (HofmeisterAn) [inline src/Testcontainers/Clients/TestcontainersClient.cs:342]:
```suggestion
        var repositoryTags = new HashSet<string>(cachedImages.Where(image => image.RepoTags != null).SelectMany(image => image.RepoTags));
```

**Review by HofmeisterAn — COMMENTED** [review]
Thank you for making us aware of the issue and immediately providing a pull request incl. a fix 🙏. I have a minor suggestion and would prefer to stick to LINQ (the `IEnumerable<T>` API). WDYT?

File: src/Testcontainers/Clients/TestcontainersClient.cs (hunk 1 above)
Comment (tom-englert) [reply src/Testcontainers/Clients/TestcontainersClient.cs:342]: Here's my thoughts:
- LINQ version optimizes the error path at cost of the happy path
- Nullable can't infer the null check from Where to the SelectMany, so whenever you turn on NRTs (which might have caught this at compile time!), you will get an NRT error in the SelectMany

However I'm open to anything, it's up to you to chose what you prefer.

Comment (tom-englert) [reply src/Testcontainers/Clients/TestcontainersClient.cs:342]: @HofmeisterAn Just give me a short notice

Comment (HofmeisterAn) [reply src/Testcontainers/Clients/TestcontainersClient.cs:342]: No, there is no need to change it. Your explanation is reasonable, and there isn't much difference (it's just my personal preference; I don't particularly like the null-coalescing operator and generally prefer LINQ).

**Review by HofmeisterAn — APPROVED** [review]

**Comment by tom-englert** [comment]
Any chance to get a release or at least a beta with this fix?

**Comment by HofmeisterAn** [comment]
I would like to include the builder logging API in the next release as well. I can publish a pre-release as soon as the pull request is merged. I am waiting for some feedback.

**Comment by HofmeisterAn** [comment]
[Here](https://www.nuget.org/packages/Testcontainers/3.8.0-beta.8238206979) you are. Sorry for the delay; I wanted to ship the logging API changes in the beta version too.
